### ISSUE TITLE
Uncaught Error: Invalid XML: <html><head><title>XQueryServlet Error</title><link rel="stylesheet"...

### ISSUE THREAD

**Issue by joewiz** [eXist-db/atom-existdb#14]
[Enter steps to reproduce:]

1. Enter the following query into a new window (with Edit > Grammar > XQuery):

```xquery
hc:send-request(<http:request href="https://history.state.gov/open/frus-latest.xml" method="get"/>)
```

2. Hit ctrl-return to submit the query.

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [existdb](https://github.com/wolfgangmm/atom-existdb) package 0.4.1

### Stack Trace

Uncaught Error: Invalid XML: <html><head><title>XQueryServlet Error</title><link rel="stylesheet" type="text/css" href="error.css"></link></head><body><h1>Error found</h1>
<div class='message'><b>Message: </b>Error</div><div class='description'><pre>err:XPST0081 No namespace defined for prefix http [at line 1, column 18, source: hc:send-request(<http:request href="https://history.state.gov/open/frus-latest.xml" method="get"/>)]</pre></div></body></html>

```
At /Users/joe/.atom/packages/existdb/node_modules/jquery/dist/jquery.js:253

Error: Invalid XML: <html><head><title>XQueryServlet Error</title><link rel="stylesheet" type="text/css" href="error.css"></link></head><body><h1>Error found</h1>
<div class='message'><b>Message: </b>Error</div><div class='description'><pre>err:XPST0081 No namespace defined for prefix http [at line 1, column 18, source: hc:send-request(<http:request href="https://history.state.gov/open/frus-latest.xml" method="get"/>)]</pre></div></body></html>
    at Function.error (/packages/existdb/node_modules/jquery/dist/jquery.js:253:9)
    at Function.jQuery.parseXML (/packages/existdb/node_modules/jquery/dist/jquery.js:7983:10)
    at Request._callback (/packages/existdb/lib/existdb.coffee:139:30)
    at Request.self.callback (/packages/existdb/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/existdb/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at /packages/existdb/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  2x -1:09.5.0 core:backspace (input.hidden-input)
     -1:08.0 core:move-right (input.hidden-input)
  2x -1:05.7.0 core:backspace (input.hidden-input)
     -1:03.5.0 core:move-right (input.hidden-input)
  2x -1:01.8.0 existdb:run (input.hidden-input)
     -0:40.2.0 application:new-file (input.hidden-input)
     -0:38.9.0 core:close (input.hidden-input)
     -0:36.8.0 application:new-file (input.hidden-input)
     -0:35.6.0 editor:split-selections-into-lines (input.hidden-input)
  2x -0:33.8.0 core:backspace (input.hidden-input)
     -0:31.2.0 editor:select-line (input.hidden-input)
  2x -0:28.2.0 editor:split-selections-into-lines (input.hidden-input)
     -0:15.9.0 grammar-selector:show (input.hidden-input)
     -0:14.7.0 core:confirm (input.hidden-input)
  2x -0:11.1.0 core:backspace (input.hidden-input)
  2x -0:06.1.0 existdb:run (input.hidden-input)
```

### Non-Core Packages

```
existdb 0.4.1 
hyperclick 0.0.40 
linter 1.11.23 
```

**Comment by duncdrum** [comment]
@joewiz the next release will have an updated jquery library can you try to reproduce with either the current head or the next release?

**Comment by joewiz** [comment]
@duncdrum Thanks, your code sample works for me. This was my mistake.
