### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onSelect' of undefined

### ISSUE THREAD

**Issue by welblaud** [eXist-db/atom-existdb#30]
[Enter steps to reproduce:]

1. Open Atom or try to reconnect to a distant DB. During connecting to the database, the final step throws this. The suspicious hint could also be it asks me whether I wish to Install server-side support app (2×) but below the question is always the whole HTML code of my Home page (in the app).

**Atom**: 1.25.0-beta2 ia32
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [existdb](https://github.com/eXist-db/atom-existdb) package 0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'onSelect' of undefined

```
At D:\C_temp\Atom\atom_custom_storage\packages\existdb\lib\existdb-tree-view.coffee:173

TypeError: Cannot read property 'onSelect' of undefined
    at Request._callback (/packages/existdb/lib/existdb-tree-view.coffee:173:39)
    at Request.self.callback (/packages/existdb/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at /packages/existdb/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at /packages/existdb/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
  3x -4:20 settings-view:open (ul.list-inline.tab-bar.inset-panel)
  2x -3:58.7.0 core:confirm (input.hidden-input)
     -2:05.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-caprice-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-ide-ui 0.9.2 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-runner 2.7.1 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
caprice-dark-syntax 2.0.0 
deep-purple-syntax 0.2.18 
duotone-dark-sky-syntax 2.1.0 
existdb 0.8.0 
hyperclick 0.0.0 
ide-java 0.8.1 
ide-typescript 0.7.5 
idle-theme 0.1.0 
intentions 1.1.5 
joehannes-steampunk-ui 0.2.11 
linter 2.2.0 
linter-ui-default 1.6.10 
monokai 0.24.0 
script 3.17.3 
steam-pirate-ui 0.6.1 
```

**Comment by welblaud** [comment]
It seems updating to another Atom version (beta3) helped, now it throws another warning. I will open another issue.
