### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sync' of undefined

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/atom-existdb#31]
steps to reproduce:
1. working in a non exist-db project
2. used git fetch
3. don't know yet what or how

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [existdb](https://github.com/eXist-db/atom-existdb) package 0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'sync' of undefined

```
At /Users/halalpha/.atom/packages/existdb/lib/sync.js:22

TypeError: Cannot read property 'sync' of undefined
    at /packages/existdb/lib/sync.js:22:39
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at didChangeCallback (/Applications/Atom.app/Contents/Resources/app/src/project.js:357:28)
    at PathWatcher.onNativeEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:671:15)
    at /Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:448:26)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:177:15)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.0 
atom-bootstrap3 1.2.12 
atom-html-preview 0.2.5 
atom-live-server 2.2.0 
atom-xmlvalidate 0.5.0 
atom-xsltransform 1.0.0 
autocomplete-bibtex 1.2.1 
busy-signal 1.4.3 
emmet 2.4.3 
existdb 0.8.0 
file-icons 2.1.17 
hyperclick 0.1.5 
intentions 1.1.5 
language-jsoniq 1.8.0 
linter 2.2.0 
linter-autocomplete-jing 0.8.2 
linter-markdown 5.2.0 
linter-ui-default 1.7.1 
linter-xmllint 1.4.3 
logo-file-icons 1.13.0 
markdown-footnote 1.1.0 
minimap 4.29.8 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
tablr 1.8.3 
teletype 0.9.0 
wordcount 2.10.4 
xml-common-schemata 0.0.3 
xml-tools 0.2.1 
```

**Comment by joewiz** [comment]
Did you have an .existdb.json file in any open Project Folders? Would git pull have altered files in any of these folders?

**Comment by duncdrum** [comment]
nope only open project has nothing to do with exist, has never had an existdb.json, and exist was not running on localhost.

**Comment by duncdrum** [comment]
I haven't been able to trigger the error again all day. Might have just been an after-effect of updating atom.
