### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by datavectors** [eXist-db/atom-existdb#33]
[Enter steps to reproduce:]

1. The one  problem I have right now is failing to upload from Atom an *.xml file to a target collection in a running instance of eXist-db.

2. I have Atom package existdb installed, eXist-db running, and I can see eXist-db tree view in Atom right pane. I am assuming from the Readme.md that this package is identical to atom-existdb.

3, I did inspect the eXist Database tree-view and I see /db/apps/atom-editor/ installed

4. In there I see the file .existdb.json and there are localhost default settings.
I had to set these to be identical to those I had previously setup in Atom existdb configuration.
Then in Atom I reapplied Packages > existdb > Reconnect
Unfortunately that did not cure the problem of not being able to upload an Atom xml file to a collection.

5. I select a target collection (folder) in eXist-db tree view.
I place my cursor in xml file to be uploaded.
I then go to Packages > existdb > Upload Current File
and I get this error message as set out below.  ...

Uncaught TypeError: Cannot read property 'type' of undefined
/home/dl/.atom/packages/existdb/lib/existdb-tree-view.coffee:390

6. I tried uploading the file directly (without Atom) as described here.
https://exist-db.org/exist/apps/doc/uploading-files
Collection Browser > Upload resources button
This works as expected, so the xml file is valid and server is working.

7. I deleted the uploaded test file using the Atom existdb client and started again through Atom existdb client. There is a full stack trace appended below ..

8. I inspected line 390 in existdb-tree-view.coffee
This is what I have ..

388        uploadCurrent: () =>
389            selected = @treeView.getSelected()
390            if selected.length != 1 or selected[0].item.type == "resource"
391                atom.notifications.addError("Please select a single target collection for the upload in the database tree view")
392                return

FULL REPORT FOLLOWS:
**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Ubuntu 16.04.5
**Thrown From**: [existdb](https://github.com/eXist-db/atom-existdb) package 0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'type' of undefined

```
At /home/dl/.atom/packages/existdb/lib/existdb-tree-view.coffee:390

TypeError: Cannot read property 'type' of undefined
    at EXistTreeView.module.exports.EXistTreeView.uploadCurrent (/packages/existdb/lib/existdb-tree-view.coffee:390:57)
    at EXistTreeView.uploadCurrent (/packages/existdb/lib/existdb-tree-view.coffee:1:1)
    at /packages/existdb/lib/existdb-tree-view.coffee:95:18)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
  3x -6:57 core:backspace (input.hidden-input)
  2x -6:33.6.0 core:save (input.hidden-input)
     -4:50.3.0 existdb:upload-current (atom-pane.pane.active)
     -4:25.4.0 existdb:reconnect (atom-pane.pane.active)
  2x -2:58.8.0 existdb:upload-current (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-beautify 0.33.0 
atom-ctags 5.1.2 
atom-html-preview 0.2.5 
atom-runner 2.7.1 
script 3.18.1 
atom-shell-commands 1.5.0 
atom-wrap-in-tag 0.6.0 
autocomplete-R 0.6.0 
autosave-onchange 1.5.1 
build 0.70.0 
build-rscript 0.6.2 
busy-signal 1.4.3 
counter 0.3.5 
emmet 2.4.3 
existdb 0.8.0 
file-icons 2.1.24 
Hydrogen 2.5.1 
hyperclick 0.1.5 
intentions 1.1.5 
language-markdown 0.26.0 
language-r 0.4.2 
latex 0.50.0 
linter 2.2.0 
linter-ui-default 1.7.1 
markdown-footnote 1.1.5 
markdown-preview-enhanced 0.15.6 
markdown-preview-plus 3.5.0 
markdown-table-editor 1.1.1 
markdown-writer 2.9.0 
process-palette 0.17.0 
project-manager 3.3.6 
r-exec 0.5.0 
scribus-composer 0.0.0 
sourcefetch 0.1.0 
svg-preview 0.12.1 
tidy-markdown 3.0.1 
tool-bar 1.1.7 
tool-bar-markdown-writer 0.4.0 
wordcount 3.0.0 
```

**Comment by joewiz** [comment]
I can reproduce the issue using the steps provided here. In addition, I should say that I am using eXist-db 4.3.1.
